services:
  db:
    image: postgres:15
    container_name: process_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: process_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: process_redis
    ports:
      - "6379:6379"

  process_service:
    build: .
    container_name: process_service
    env_file:
      - .env
    environment:
      PROCESS_DATABASE_URL: ${PROCESS_DATABASE_URL}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_DB: ${REDIS_DB}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_SESSION_TOKEN: ${AWS_SESSION_TOKEN}
      S3_BUCKET_NAME: ${S3_BUCKET_NAME}
      AWS_REGION_NAME: ${AWS_REGION_NAME}
    depends_on:
      - db
      - redis
    ports:
      - "8003:8000" 

volumes:
  pgdata:
